Online_books/Online_books/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect


def redirect_view(request):
    response = redirect('/accounts/login/')
    return response

urlpatterns = [
    path('librarian/', admin.site.urls),
    path('', redirect_view),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', include('personal_books.urls')),
    # path('', include('personal_books.urls')),

]

Online_books/personal_books/urls.py
from django.urls import path
from .views import (home, add
                    )

app_name = "personal_books"

urlpatterns = [
    path('', home, name='home'),
    path("add/", add, name='add'),
    # path('subscribe/',subscribe,name='subscribe'),
    # path('custom/',custom,name="custom")
    # path('checkout/', CheckoutView.as_view(), name='checkout'),
    # path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    # path('product/<slug>/', ItemDetailView.as_view(), name='product'),

]

Online_books/personal_books/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
CATEGORY_CHOICES = (
    ('P', 'Physical'),
    ('E', 'Ebook'),
)
genre_list = (
    ("F", "Fantasy"),
    ("D", "Dystopian"),
    ("S", "Science fiction"),
    ("M", "Mystery"),
    ("H", "Horror"),
    ("R", "Romance"),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Books(models.Model):
    user1 = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    Title = models.CharField(max_length=100,unique=True)
    Author = models.CharField(max_length=100)
    Genre = models.CharField(choices=genre_list,max_length=40)
    Type = models.CharField(choices=CATEGORY_CHOICES,max_length=1)
    Rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    Review = models.CharField(max_length=100)
    Favorite = models.BooleanField(default=False)


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

Online_books/personal_books/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from .models import Books, UserProfile
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.urls import reverse
from django.http import HttpResponse

global flag


def home(request):
    global flag
    flag = False
    obj = None
    print("request.home", request.POST)
    if request.method == "POST":
        if "read" in request.POST:
            obj = Books.objects.get(Title=request.POST["read"])
            flag = True
            nochange = True

            return render(request, "display_form.html", {"obj": obj, "flag": flag, "nochange": nochange})
        elif "update" in request.POST:
            flag = True
            obj = Books.objects.get(Title=request.POST["update"])
            return render(request, "display_form.html", {"obj": obj, "flag": flag}, )
        elif "delete" in request.POST:
            delete1(request.POST["delete"])
        elif "title" in request.POST:
            return add(request)

    obj = Books.objects.filter(user1=UserProfile.objects.get(user=request.user))

    return render(request, "index.html", {"obj": obj, "user": request.user})


def add(request):
    if request.method == "POST":
        flag1 = False
        rating = 1
        if "fav" in request.POST and request.POST["fav"] == 'on': flag1 = True
        if "rating" in request.POST and request.POST["rating"] != "":
            if 1 <= int(request.POST["rating"]) >= 5: rating = int(request.POST["rating"])
        if len(Books.objects.filter(Title=request.POST["title"])) == 0:

            try:
                b = Books.objects.create(user1=UserProfile.objects.get(user=request.user), Title=request.POST["title"],
                                         Author=request.POST["author"], Genre=request.POST["genre"]
                                         , Type=request.POST["type"], Rating=rating, Review=request.POST["review"],
                                         Favorite=flag1)

                b.save()
            except:
                print("finished")
        else:
            print("here")
            Books.objects.filter(Title=request.POST["title"]).update(Author=request.POST["author"],
                                                                     Genre=request.POST["genre"]
                                                                     , Type=request.POST["type"], Rating=rating,
                                                                     Review=request.POST["review"],
                                                                     Favorite=flag1)
        obj = Books.objects.filter(user1=UserProfile.objects.get(user=request.user))
        print("before redirect",obj)
        return redirect("/")

    return render(request, "display_form.html")



def delete1(title_name):
    Books.objects.filter(Title=title_name).delete()
    return

Online_books/personal_books/templates/display_form.html
{% include "navbar.html" %}

<body style="background-color:#669999;">

<h2 >Book Details</h2>
<form method="post" class="col-md-10" >
    {% csrf_token %}
  <div class="form-group row">
    <label for="title" class="col-sm-1 col-form-label">Title</label>
      <div class="col-sm-10">
    <input type="text" class="form-control" id="title"  name="title" required>
          </div>
  </div>

     <div class="form-group row">
    <label class="col-sm-1 col-form-label">Genre</label>
    <div class="col-sm-3">
  <select class="form-control " default="Fantasy" id="genre" name="genre">
    <option value="Fantasy">Fantasy</option>
    <option value="Dystopian">Dystopian</option>
       <option value="Mystery">Mystery</option>
       <option value="Science fiction">Science fiction</option>
       <option value="Horror">Horror</option>
       <option value="Romance">Romance</option>

  </select>
    </div>
         </div>
  </div>
      </div>
     <div class="form-group row">
    <label for="author" class="col-sm-1 col-form-label" >Author</label>
         <div class="col-sm-10">
    <input type="text" class="form-control" id="author" name="author" required>
         </div>
  </div>

     <div class="form-group row">
    <label class="col-sm-1 col-form-label">Type</label>
    <div class="col-sm-3">
  <select class="form-control " id="type" default="P" name="type">
    <option value="P">Physical</option>
    <option value="E">Ebooks</option>

  </select>
    </div>
         </div>
  </div>
     <div class="form-group row">
    <label for="rating" class="col-sm-1 col-form-label">Rating</label>
         <div class="col-sm-1">
    <input type="number" class="form-control" id="rating"  name="rating" default="1" min="1" max="5" placeholder="1">
         </div>
         </div>

    <div class="form-group row">
    <label for="review" class="col-sm-1 col-form-label">Review</label>
        <div class="col-sm-10">
            <textarea  class="form-control" id="review" name="review" rows="10" placeholder="comments" required></textarea>
        </div>
  </div>

      <div class="form-group row ">
    <label for="fav1" class="col-sm-1 col-form-label">Favourite</label>
          <div class="col-md-2">
        <input type="checkbox" class="form-control" id="fav1"   name="fav1" >
          </div>
          <input  type="Submit" id="sub" style="position:absolute;right:130px;">
  </div>

</form>
{% if flag %}
    <script>

      document.getElementById("title").value = "{{obj.Title}}";
      document.getElementById("genre").value = "{{obj.Genre}}";
      document.getElementById("type").value = "{{obj.Type}}";
      document.getElementById("author").value = "{{obj.Author}}";
      document.getElementById("rating").value = "{{obj.Rating}}";
      document.getElementById("review").value = "{{obj.Review}}";
 {% if "{{obj.Favorite}}" is false %}
      document.getElementById("fav1").checked =false;
      {% elif "{{obj.Favorite}}" is true %}
       document.getElementById("fav1").checked = true;
       {% endif %}
      document.getElementById('title').setAttribute('readonly', true);
      {% if nochange %}
      document.getElementById('sub').setAttribute('disabled', true);
      document.getElementById('genre').setAttribute('disabled', true);
      document.getElementById('type').setAttribute('disabled', true);
      document.getElementById('author').setAttribute('readonly', true);
      document.getElementById('rating').setAttribute('readonly', true);
      document.getElementById('review').setAttribute('readonly', true);
      document.getElementById('fav1').setAttribute('disabled', true);
      {% endif %}
    </script>
{% endif %}
</body>
</html>

Online_books/personal_books/templates/index.html
{% include "navbar.html" %}

 <body style="background-color:#669999;"  >
  <div class="w3-container">

  <h2 class="font-weight-bold indigo-text">Personal Book Store  ---> {{user}}</h2>
  <p>Below are the Books added by you</p>
  <table class="table">
    <thead>
    <tr class="">
      <th scope="col">Title</th>
      <th scope="col">Genre</th>
      <th scope="col">Author</th>
      <th scope="col">Rating </th>
        <th></th>
          <th></th>
          <th></th>
    </tr>
    </thead>
    <tbody>
      {% for o in obj %}

    <tr class="rowgroup">
      <th scope="row">{{o.Title}}</th>
      <th scope="row">{{o.Genre}}</th>
      <th scope="row">{{o.Author}}</th>
      <th scope="row">{{o.Rating}}</th>
      <th scope="row">
        <form method="post" >
            {% csrf_token %}
        <input type="hidden" name="read" value="{{o.Title}}">
        <button type="submit">Read</button>
        </form>
      </th>
      <th scope="row">
        <form method="post" >
            {% csrf_token %}
        <input type="hidden" name="update" value="{{o.Title}}">
        <button type="submit">Update</button>
        </form>
      </th>
       <th scope="row">
        <form method="post" >
            {% csrf_token %}
        <input type="hidden" name="delete" value="{{o.Title}}">
        <button type="submit">Delete</button>
        </form>
      </th>
    </tr>

    {% endfor %}

</tbody>
  </table>
  </div>

</body>

Online_books/personal_books/templates/navbar.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Books</title>
  </head>

<nav class="navbar navbar-light bg-light" >
  <a class="navbar-brand"  href="{% url 'personal_books:home' %}">Book Store</a>

  <div class="navbar-nav" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="navbar navbar-light bg-light " style="position:absolute;right:200px;" >

            <a href="{% url 'personal_books:add' %}">
              <button class="btn btn-outline-success" type="button">Add book</button>
            </a>

      </li>
      <li class="nav-item" >
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="btn btn-outline-success"> Logout </span>
            </a>
          </li>
    </ul>
  </div>
</nav>

</html>